#!/usr/bin/env python3
"""
Compare plant vs mammalian optimization for the same protein.
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path
from typing import Dict, Tuple

from Bio import SeqIO

from factorforge.engines.ml.plant_optimizer import PlantCodonOptimizer


def setup_logging(verbose: bool) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(level=level, format="%(levelname)s: %(message)s")


def read_protein_fasta(path: Path) -> Tuple[str, str]:
    records = list(SeqIO.parse(str(path), "fasta"))
    if not records:
        raise ValueError(f"No FASTA records found in {path}")
    record = records[0]
    return record.id, str(record.seq)


def format_table(metrics: Dict[str, Dict[str, float]]) -> str:
    lines = []
    lines.append("| Metric              | Plant      | Mammalian  |")
    lines.append("|---------------------|------------|------------|")
    lines.append(
        f"| Changed codons      | {metrics['plant']['changed_codons']}/{metrics['plant']['total_codons']}    "
        f"| {metrics['mammalian']['changed_codons']}/{metrics['mammalian']['total_codons']}     |"
    )
    lines.append(
        f"| CAI original        | {metrics['plant']['original_cai']:.2f}       "
        f"| {metrics['mammalian']['original_cai']:.2f}       |"
    )
    lines.append(
        f"| CAI optimized       | {metrics['plant']['optimized_cai']:.2f}       "
        f"| {metrics['mammalian']['optimized_cai']:.2f}       |"
    )
    lines.append(
        f"| CAI improvement     | {metrics['plant']['cai_improvement']:+.2f}      "
        f"| {metrics['mammalian']['cai_improvement']:+.2f}      |"
    )
    lines.append(
        f"| GC content original | {metrics['plant']['original_gc']:.2f}%     "
        f"| {metrics['mammalian']['original_gc']:.2f}%     |"
    )
    lines.append(
        f"| GC content optimized| {metrics['plant']['optimized_gc']:.2f}%     "
        f"| {metrics['mammalian']['optimized_gc']:.2f}%     |"
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare plant vs mammalian optimization.")
    parser.add_argument("--input", required=True, help="Protein FASTA path.")
    parser.add_argument("--plant-model", required=True, help="Plant model path.")
    parser.add_argument("--plant-tokenizer", required=True, help="Plant tokenizer path.")
    parser.add_argument("--plant-codon-table", required=True, help="Plant codon table path.")
    parser.add_argument("--mammalian-model", required=True, help="Mammalian model path.")
    parser.add_argument("--mammalian-tokenizer", required=True, help="Mammalian tokenizer path.")
    parser.add_argument(
        "--mammalian-codon-table", required=True, help="Mammalian codon table path."
    )
    parser.add_argument("--output", required=True, help="Comparison report output path.")
    parser.add_argument("--beam-size", type=int, default=5, help="Beam search size.")
    parser.add_argument("--verbose", action="store_true", help="Verbose logging.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    setup_logging(args.verbose)

    try:
        protein_name, protein_seq = read_protein_fasta(Path(args.input))
    except Exception as exc:
        logging.error("Input error: %s", exc)
        return 1

    logging.info("Protein: %s (%d aa)", protein_name, len(protein_seq))
    plant = PlantCodonOptimizer(
        model_path=args.plant_model,
        codon_table_path=args.plant_codon_table,
        tokenizer_path=args.plant_tokenizer,
        organism="plant",
    )
    mammalian = PlantCodonOptimizer(
        model_path=args.mammalian_model,
        codon_table_path=args.mammalian_codon_table,
        tokenizer_path=args.mammalian_tokenizer,
        organism="mammalian",
    )

    logging.info("Optimizing with plant model...")
    plant_dna = plant.optimize(protein_seq, beam_size=args.beam_size)
    logging.info("Optimizing with mammalian model...")
    mammalian_dna = mammalian.optimize(protein_seq, beam_size=args.beam_size)

    plant_original = plant._reverse_translate(protein_seq)
    mammalian_original = mammalian._reverse_translate(protein_seq)

    metrics = {
        "plant": plant.compare_sequences(plant_original, plant_dna),
        "mammalian": mammalian.compare_sequences(mammalian_original, mammalian_dna),
    }

    report = []
    report.append("Codon Optimizer Comparison Report")
    report.append("=" * 60)
    report.append(f"Protein: {protein_name}")
    report.append(f"Length: {len(protein_seq)} aa")
    report.append("")
    report.append("Notes: Original DNA is generated by most-frequent codons per organism.")
    report.append("")
    report.append(format_table(metrics))
    report_text = "\n".join(report)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report_text, encoding="utf-8")
    logging.info("Comparison report written to %s", output_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
